spring.application.name=reservation_system

# 1. Database Connection (PostgreSQL)
spring.datasource.url=jdbc:postgresql://postgres:5432/bakery_db
spring.datasource.username=bakery_admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA & Hibernate Optimization
spring.jpa.hibernate.ddl-auto=update
# 부하 테스트 시 SQL 로그 출력은 성능 저하의 주범이므로 반드시 끕니다.
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# 3. HikariCP Connection Pool
# VUS 100 환경을 고려하여 풀 사이즈를 넉넉하게 조정합니다.
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.pool-name=BakeryHikariPool

# 4. Redis Configuration (Docker Network)
spring.data.redis.host=redis
spring.data.redis.port=6379

# 5. Kafka Producer Optimization (비동기 성능의 핵심)
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.producer.acks=1
spring.kafka.producer.batch-size=16384
spring.kafka.producer.properties.linger.ms=5
spring.kafka.producer.buffer-memory=33554432

logging.level.root=WARN
logging.level.com.example.reservation_system=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.com.zaxxer.hikari=WARN